spring.application.name=ProductService

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=secret
server.port=${PORT_NO}
jwt.secret=${JWT_SECRET}
